Repository hlxsites/aem-boilerplate-commerce, pull requests merged in 2024-10, with the labels that each got.

#120 Allow customizing the API url for product listing page widget
  blocks/product-list-page/product-list-page.js
  scripts/widgets/search.js
Labels: bug

#122 Add support for multiple configs to product picker
  tools/picker/README.md
  tools/picker/dist/index.515784d0.js
  tools/picker/dist/index.6210969e.js
  tools/picker/dist/index.html
  tools/picker/src/index.js
  tools/picker/src/picker.js
Labels: changelog

#130 Product recommendation event fixes
  blocks/product-recommendations/product-recommendations.js
  scripts/scripts.js
Labels: bug, changelog

#106 Dropin Build Tools (GraphQl Operations Extensibility)
  .hlxignore
  build.mjs
  package-lock.json
  package.json
  postinstall.js
  scripts/__dropins__/storefront-cart/fragments.original.js
  scripts/commerce-events-collector.js
Labels: DO NOT MERGE

#78 Add expiry to config session storage cache
  scripts/configs.js
Labels: changelog

#140 CAED-67 Checkout issues
  scripts/scripts.js
Labels: bug

#159 Update recommendationsContext and productContext to include only required data
  blocks/product-details-custom/product-details-custom.js
  blocks/product-recommendations/product-recommendations.js
  blocks/product-teaser/product-teaser.js
  scripts/commerce.js
Labels: bug, changelog
