Repository hlxsites/aem-boilerplate-commerce, pull requests merged in 2024-07, with the labels that each got.

#70 add wishlist implementation
  blocks/product-details/product-details.css
  blocks/product-details/product-details.js
  scripts/wishlist/api.js
Labels: changelog

#76 Fix invalid storefront events
  blocks/product-list-page-custom/ProductList.js
  blocks/product-recommendations/product-recommendations.js
  scripts/scripts.js
Labels: bug

#79 Update PDP to v0.3.0
  blocks/product-details/product-details.js
  package-lock.json
  package.json
  scripts/__dropins__/storefront-pdp/containers/ProductDetails.js
  scripts/__dropins__/storefront-pdp/containers/ProductDetails/ProductDetails.d.ts
Labels: changelog

#71 Fix PDP 404 pages
  404.html
  blocks/product-details-custom/product-details-custom.js
  blocks/product-details/product-details.js
  scripts/commerce.js
Labels: bug, changelog

#82 Multiple Storefront Event Fixes
  blocks/product-list-page/product-list-page.js
  scripts/delayed.js
  scripts/widgets/search.js
Labels: changelog

#72 Add PDP metadata script
  .eslintignore
  .hlxignore
  tools/pdp-metadata/.gitignore
  tools/pdp-metadata/README.md
  tools/pdp-metadata/package-lock.json
  tools/pdp-metadata/package.json
  tools/pdp-metadata/pdp-metadata.js
  tools/pdp-metadata/queries/products.graphql.js
Labels: changelog

#81 Remove default query params for custom PLP
  blocks/product-list-page-custom/product-list-page-custom.js
Labels: changelog

#84 Remove case changes from product SKUs
  blocks/product-details-custom/product-details-custom.js
  blocks/product-details/product-details.js
  blocks/product-list-page-custom/ProductList.js
  blocks/product-list-page-custom/product-list-page-custom.js
  blocks/product-recommendations/product-recommendations.js
  scripts/commerce.js
  scripts/minicart/Minicart.js
  tools/pdp-metadata/pdp-metadata.js
Labels: changelog

#86 Fix loading of dropins with speculation rule pre-rendering
  scripts/dropins.js
Labels: bug
